### PR TITLE
Generator support

### PR DESCRIPTION
**Pull request by davidroth**
This is to address #20 

I have also upgraded the following iterators to use yield:

- [x] ChunkInterator
- [x] DistinctIterator
- [x] ExceptIterator
- [x] IntersectIterator
- [x] SelectManyIterator

Missing unit-tests:
- [x] Set
- [x] None primitive type operations (distinct, except etc.)

Beside the cleaner code, memory usage should be much lower when used in large streams of data.

### CODE REVIEW

**Comment by robations** [comment]
I've not checked it out properly but still getting the "Cannot rewind a generator that was already run" error with this branch.

**Comment by davidroth** [comment]
All tests are passing. Can you show me your test code which leads to the exception?

**Comment by robations** [comment]
Sure, so this is triggering the error for me:

[test-diff.txt](https://github.com/fusonic/linq/files/31793/test-diff.txt)

    Exception: Cannot rewind a generator that was already run

    src/Fusonic/Linq/Iterator/ChunkIterator.php:36

If I remove the `where` and `select` I get a different error:

    Exception: Cannot traverse an already closed generator

    src/Fusonic/Linq/Iterator/ChunkIterator.php:36

**Comment by davidroth** [comment]
Thx for your feedback. You used the ```each``` method which does eager evaluation and returns $this at the end:

```php
public function each($func)
{
	foreach ($this->iterator as $item) {
	    $func($item);
	}
	return $this;
}
```
Because of that, the subsequent ```toArray()``` call lead to the additional traversing of the generator.
I have modified your test-class and used ```select()``` instead of ```each()```.
The test is now passing.

I have also changed the ```each``` method to return ```void``` instead of ```$this```. This is a breaking change from 1.0, but returning $this is confusing and leads to wrong assumptions about the behavior of each. (as in your example). Composing over each does not make sense, so I think this is the better contract.

**Comment by robations** [comment]
Good point. `each()` should be for side-effects. Thanks for checking this out.

**Comment by robations** [comment]
Only other comments I'd have (assuming you are looking for notes, and maybe you're not :) ), I would consider creating separate unit tests for each of the iterators, as much as anything to document behaviour and help any future contributors quickly pick up regressions. Also note that some mixed whitespace (tabs/spaces) has crept into the project (see, for example, `OfTypeIterator` and near the end of `LinqTest`). Besides that, `yield` is a huge win here.

**Comment by davidroth** [comment]
Good point. I think it would also be worth, splitting the LinqTest.php into multiple files, each focused on a specific method.
Feedback and contributions always welcome :)

**Pull request merged**
